[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'unsafe-inline' 'unsafe-eval' https://akgspecialtyinc.com/; script-src 'unsafe-inline' 'unsafe-eval' https://akgspecialtyinc.com/ https://www.googletagmanager.com; style-src 'unsafe-inline' https://akgspecialtyinc.com/; img-src https://akgspecialtyinc.com/ https://res.cloudinary.com/; font-src 'self' https://akgspecialtyinc.com/; connect-src https://akgspecialtyinc.com/; media-src https://akgspecialtyinc.com/; object-src https://akgspecialtyinc.com/; child-src https://akgspecialtyinc.com/; form-action https://akgspecialtyinc.com/;"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Feature-Policy = "microphone 'none'; geolocation 'none'"