[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'none'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.netlify.app https://www.google-analytics.com https://ajax.googleapis.com; connect-src 'self'; img-src 'self' data: https://www.res.cloudinary.com; style-src 'self' 'unsafe-inline'; font-src 'self' data: ; base-uri 'self'; form-action 'self'"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Feature-Policy = "microphone 'none'; geolocation 'none'"