[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy-Report-Only = "script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.netlify.app https://www.google-analytics.com https://ajax.googleapis.com; connect-src 'self'; img-src 'self' *; style-src 'self'; font-src *; script-src-elem 'self' 'unsafe-inline'; base-uri 'self'; form-action 'self'; report-uri https://akgspecialtyinc.com/collector.cgi; default-src 'self';"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Feature-Policy = "microphone 'none'; geolocation 'none'"