[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy-Report-Only = "script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.netlify.app https://www.google-analytics.com; connect-src 'self'; img-src 'self' data: *; style-src 'self' 'unsafe-inline'; font-src data: *; script-src-elem 'self' 'unsafe-inline' https://www.googletagmanager.com; object-src 'self'; base-uri 'self'; form-action 'self'; default-src 'self';"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Feature-Policy = "microphone 'none'; geolocation 'none'"