[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "script-src https: 'self' 'unsafe-inline' https://www.googletagmanager.com netlify.app; img-src https: data: 'self' netlify.app; style-src https: 'self' 'unsafe-inline' netlify.app"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Feature-Policy = "microphone 'none'; geolocation 'none'"